### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale#10]

**Comment by joelhulen** [comment]
I suggest the following updates. Please provide your feedback:

1. The latest Npgsql provider now supports DirectQuery with Power BI. Update the WDS and, if appropriate, the lab, to reflect this change.
2. Update lab instructions with the latest UI changes for deploying Hyperscale (Citus).
3. Add high availability scenario to the WDS that prompts students to enable the high availability option for a Hyperscale cluster.
4. Update the data generator and libraries used for the lab to the latest, stable versions.

**Comment by DawnmarieDesJardins** [comment]
This June 2020 update has changed to a June test/fix.  Closing update issue.
