### ISSUE TITLE
September 2020 update suggestions

### ISSUE THREAD

**Issue by joelhulen** [microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale#12]
I suggest the following updates. Please provide your feedback:

- The latest Npgsql provider now supports DirectQuery with Power BI. Update the WDS and, if appropriate, the lab, to reflect this change.
- Update lab instructions with the latest UI changes for deploying Hyperscale (Citus).
- Add high availability scenario to the WDS that prompts students to enable the high availability option for a Hyperscale cluster.
- Update the data generator and libraries used for the lab to the latest, stable versions.
- Add exercise in the lab to use Azure Data Studio to create a PostgreSQL database health check SQL notebook, which monitors cache hit ratio, monitors dead tuples, monitors unused indexes, and monitors query performance.

**Comment by DawnmarieDesJardins** [comment]
Workshop is to be archived 12/1/20, closing update issue.
