### ISSUE TITLE
Exercise 5: Task 1: NpgSQL installation link is broken

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale#4]
[Exercise 5: Task 1:](https://github.com/microsoft/MCW-Real-time-data-with-Azure-Database-for-PostgreSQL-Hyperscale/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Real-time%20data%20with%20Azure%20Database%20for%20PostgreSQL%20Hyperscale.md#task-1-connect-to-your-postgres-data-from-power-bi)  
In Step 3, NpgSQL installation link is broken. 

![image](https://user-images.githubusercontent.com/50323628/66255568-a924f300-e7a2-11e9-9789-4ba38dd0374f.png)

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by akn9050** [comment]
Hi @timahenning, @joelhulen 

Did you review the issue.  Any update.

Thanks,
Amit Kumar
